ES = "https://search-tushar-twitt-szlyyivgcap6jdjy5up4x734bi.us-west-1.es.amazonaws.com"
TWITTER_APP_KEY = 'l5NP1KQZxSvlAqNOd5pfKpe8r'
TWITTER_APP_KEY_SECRET = 'pBepdXoxDjREgqjeSQYltBqJ9PGKoXUtMgOXJOOZwdO88AAvTF'
TWITTER_ACCESS_TOKEN = '2407434150-29RUn5YRhBQOZgSUEy5HnjjTdPIIlSYgzZHGduL'
TWITTER_ACCESS_TOKEN_SECRET = '4hUMANOqyxVjfw0i0uAIbEOYsqs25IDD7bHPE3AP5QKEw'
